Repository jupyter-server/pytest-jupyter, pull requests merged in 2022-12, with the labels that each got.

#34 hoist __version__
  pytest_jupyter/__init__.py
Labels: maintenance

#37 Adopt ruff and address lint
  .github/dependabot.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pyproject.toml
  pytest_jupyter/jupyter_server.py
  pytest_jupyter/pytest_tornasync.py
  tests/test_jupyter_server.py
Labels: maintenance

#36 Use native kernel by default
  .github/workflows/test.yml
  pytest_jupyter/jupyter_client.py
  pytest_jupyter/jupyter_server.py
  tests/test_jupyter_client.py
Labels: enhancement

#38 Fix core import in client
  pytest_jupyter/jupyter_client.py
Labels: bug

#40 Handle TimeoutError During Fixture Shutdown
  .github/workflows/test.yml
  pytest_jupyter/jupyter_server.py
  tests/test_jupyter_server.py
Labels: bug

#41 Handle asyncio timeout
  pytest_jupyter/jupyter_server.py
Labels: bug

#42 Add more ci checks
  .github/workflows/test.yml
  .pre-commit-config.yaml
  docs/conf.py
  pyproject.toml
  pytest_jupyter/_version.py
  pytest_jupyter/echo_kernel.py
  pytest_jupyter/jupyter_client.py
  pytest_jupyter/jupyter_core.py
  pytest_jupyter/jupyter_server.py
  pytest_jupyter/pytest_tornasync.py
  pytest_jupyter/utils.py
Labels: maintenance

#45 Clean up lint
  pyproject.toml
  pytest_jupyter/jupyter_server.py
Labels: maintenance
