Repository jupyter-server/pytest-jupyter, pull requests merged in 2024-04, with the labels that each got.

#78 jp_ws_fetch: passthrough kwargs to websocket_connect
  pytest_jupyter/jupyter_server.py
Labels: enhancement

#80 Set all min deps
  pyproject.toml
Labels: maintenance

#81 Fix passing of kwargs to websocket_connect
  pytest_jupyter/jupyter_server.py
Labels: bug
